@teacher_token = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVEVBQ0hFUiJdLCJ1c2VybmFtZSI6IjYyMzQ1Njc4OSIsInN1YiI6IjYyMzQ1Njc4OSIsImlhdCI6MTc2Nzc2NjA1NywiZXhwIjoxNzY3ODUyNDU3fQ.UeeA453QBRza0zovFiMRWOrcvNUNYRfBlZqB6Fhfxs6V78uWjrkTms9TOqVEGSmWIDzQouQrh_yXQesAn223Ww

### 2. Davomatni belgilash (Set Attendance)
POST http://localhost:8080/v1/attendance/set-attendance/teacher
Authorization: Bearer {{teacher_token}}
Content-Type: application/json

{
  "studentId": "06b2bc1b-6ece-450b-9d40-bf6937b74d77",
  "scheduleId": "16f04585-caa6-4b0c-9beb-c2b013bc38d4",
  "schoolId": "a84a424f-7823-4fc6-b9d0-9dde6f00eeb2",
  "subjectId": 1,
  "groupId": "d2d5a47a-5d76-4d6f-b843-d22afa95d2fc",
  "status": "PRESENT",
  "reason": "kasal",
  "date": "2026-01-12"
}

### 3. Davomatni yangilash (Update)
PUT http://localhost:8080/v1/attendance/update/teacher/fe3c4111-e15f-4e4e-93bf-ed444f807deb
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "status": "REASONABLE",
  "reason": "Sababli (kasallik varaqasi)"
}

### 4. Talaba bo'yicha davomat ro'yxatini olish
GET http://localhost:8080/v1/attendance/get-by-student/087bfba3-92a6-4995-a43f-9cab0d74e8e6
Authorization: Bearer {{auth_token}}

### 5. Guruh bo'yicha davomat ro'yxatini olish
GET http://localhost:8080/v1/attendance/get-by-group/guruh-uuid-bu-yerga
Authorization: Bearer {{auth_token}}

### 6. Davomatni o'chirish
DELETE http://localhost:8080/v1/attendance/delete/teacher/davomat-uuid-bu-yerga
Authorization: Bearer {{auth_token}}

### Talabaning 95% lik vidjeti uchun ma'lumot olish
GET http://localhost:8080/v1/attendance/stats/087bfba3-92a6-4995-a43f-9cab0d74e8e6?subjectId=1
Authorization: Bearer {{auth_token}}
Accept: application/json

### 1. Talabaning oylik davomat grafigi (Monthly Overview Chart)
GET http://localhost:8080/v1/attendance/monthly-overview/db112066-8b5c-44ee-bfd4-24ecf8c72f7f
Authorization: Bearer {{auth_token}}
Accept: application/json