### LOGIN
POST localhost:8080/v1/auth/login
Content-Type: application/json

{
  "passportNumber": "62",
  "password": "12345"
}

### CREATE ADMIN
POST localhost:8080/v1/auth/registration/moderator
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3Njc1MTgzNTIsImV4cCI6MTc2NzYwNDc1Mn0.klVdSZzjvmnEwjd1kiZGwn2N_tNiY-Ci2iemj0Sjfz_SHTdT6NNetgg7p4CD6DNgZIIXXEeSiyJla8Km__9cvw
Content-Type: application/json

{
  "firstName": "asilbek",
  "lastName": "xolmuminov",
  "patronymic": "anvarovich",
  "birthDate": "2003-11-14",
  "password": "12345678",
  "gender": "MALE",
  "pinfl": "12345678901015",
  "passportSeries": "AB",
  "passportNumber": "123456701",
  "roles": ["ROLE_ADMIN"],
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e"
}

### CREATE TEACHER OR STUDENT
POST localhost:8080/v1/auth/registration/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3Njc1MTg1NDYsImV4cCI6MTc2NzYwNDk0Nn0.gNp4cWxlbIi4wA56aet4TeRT41D9nu8REuVFKinQk3QqmVrEyp8_pcGY4fTy4hyK-5hzuAWjl6RdkmsTmp1G_w
Content-Type: application/json

{
  "firstName": "asilbek",
  "lastName": "xolmuminov",
  "patronymic": "anvarovich",
  "birthDate": "2003-11-14",
  "password": "12345",
  "gender": "MALE",
  "pinfl": "623",
  "passportSeries": "AB",
  "passportNumber": "623",
  "roles": ["ROLE_STUDENT"],
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e"
}

### GET BY ID (MODERATOR)
GET localhost:8080/v1/auth/get/moderator/5637883b-d3f1-43c6-97e4-3f647c2be3e1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjcxODg4NTEsImV4cCI6MTc2NzI3NTI1MX0.pTyDOjzCKzCC07rTv_vftC3aQNggqr4UjUtKsY7bG9gK8GTp8gnGhK1rXXQSTO4ovZUht3BvMNfalHSGc0u2Xg

### GET BY ID (ADMIN)
GET localhost:8080/v1/auth/get/admin/5637883b-d3f1-43c6-97e4-3f647c2be3e1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3NjcxODkwODksImV4cCI6MTc2NzI3NTQ4OX0.aY4Q34y5zXrbR0yGswFjyrZ7Ufe7j_j9jVQOZiPAj2N6hLVa-jjTWfssNlGWa5hR80yhqEFptsKsvKph9o7wnw

### UPDATE (MODERATOR)
PUT localhost:8080/v1/auth/update/moderator/5637883b-d3f1-43c6-97e4-3f647c2be3e1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjcxODg4NTEsImV4cCI6MTc2NzI3NTI1MX0.pTyDOjzCKzCC07rTv_vftC3aQNggqr4UjUtKsY7bG9gK8GTp8gnGhK1rXXQSTO4ovZUht3BvMNfalHSGc0u2Xg
Content-Type: application/json

{
  "name": "tinchku",
  "roleList": ["ROLE_TEACHER"]
}

### UPDATE (ADMIN)
PUT localhost:8080/v1/auth/update/admin/5637883b-d3f1-43c6-97e4-3f647c2be3e1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3NjcxODkwODksImV4cCI6MTc2NzI3NTQ4OX0.aY4Q34y5zXrbR0yGswFjyrZ7Ufe7j_j9jVQOZiPAj2N6hLVa-jjTWfssNlGWa5hR80yhqEFptsKsvKph9o7wnw
Content-Type: application/json

{
  "name": "tinchku"
}

### LIST
GET localhost:8080/v1/auth/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjcxODg4NTEsImV4cCI6MTc2NzI3NTI1MX0.pTyDOjzCKzCC07rTv_vftC3aQNggqr4UjUtKsY7bG9gK8GTp8gnGhK1rXXQSTO4ovZUht3BvMNfalHSGc0u2Xg

### DELETE (MODERATOR)
DELETE localhost:8080/v1/auth/moderator/delete/5637883b-d3f1-43c6-97e4-3f647c2be3e1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjcxODg4NTEsImV4cCI6MTc2NzI3NTI1MX0.pTyDOjzCKzCC07rTv_vftC3aQNggqr4UjUtKsY7bG9gK8GTp8gnGhK1rXXQSTO4ovZUht3BvMNfalHSGc0u2Xg

### DELETE (ADMIN)
DELETE localhost:8080/v1/auth/admin/delete/a3435343-a864-4209-84f9-690bf0f70976
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY2OTMwMDAwLCJleHAiOjE3NjcwMTY0MDB9.vltcgQrOQQoHY1RVaxyW5My-r_EL_ejcul17nYj5f87lZbhHy21Efeop8-nQM8yrbeISy9GZEppvJAvsEdMNoA

### UPDATE PASSWORD
PUT localhost:8080/v1/auth/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3NjcxODkwODksImV4cCI6MTc2NzI3NTQ4OX0.aY4Q34y5zXrbR0yGswFjyrZ7Ufe7j_j9jVQOZiPAj2N6hLVa-jjTWfssNlGWa5hR80yhqEFptsKsvKph9o7wnw

{
  "oldPassword": "12345678",
  "newPassword": "123456789"
}

### FILTER
POST localhost:8080/v1/auth/filter
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjcxODg4NTEsImV4cCI6MTc2NzI3NTI1MX0.pTyDOjzCKzCC07rTv_vftC3aQNggqr4UjUtKsY7bG9gK8GTp8gnGhK1rXXQSTO4ovZUht3BvMNfalHSGc0u2Xg
Content-Type: application/json

{
  "role": "ROLE_ADMIN",
  "status": "ACTIVE"
}

> {% client.global.set("jwt", response.body.jwt); %}