### LOGIN
POST localhost:8080/v1/auth/login
Content-Type: application/json

{
  "passportNumber": "12345679",
  "password": "123456789"
}

### CREATE ADMIN
POST localhost:8080/v1/auth/registration/moderator
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY5MjA1ODMsImV4cCI6MTc2NzAwNjk4M30.PC_X-3PUULTzc2J3RQec2HSNCO-aPlnx_HoUR0ucunfVGg66YWRKN5ZtDpE8PBlcD-CZFHEGQvQXE1d9zbDyTQ
Content-Type: application/json

{
  "firstName": "asilbek",
  "lastName": "xolmuminov",
  "patronymic": "anvarovich",
  "birthDate": "2003-11-14",
  "password": "12345678",
  "gender": "MALE",
  "pinfl": "12345678901012",
  "passportSeries": "AB",
  "passportNumber": "12345679",
  "roles": ["ROLE_ADMIN"],
  "schoolId": "7cf08c00-d823-433d-adc6-c05ac07cd21b"
}

### CREATE TEACHER OR STUDENT
POST localhost:8080/v1/auth/registration/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NSIsInN1YiI6IjEyMzQ1IiwiaWF0IjoxNzY2OTI0NTYzLCJleHAiOjE3NjcwMTA5NjN9.G-42o6HPltsqyjNufUhMjLZcP2ek3yMKeibGO56o4kTz9sY9DXmPezRXqqa1kn3xDvIqPt-skbDENfybgJqSmw
Content-Type: application/json

{
  "firstName": "asilbek",
  "lastName": "xolmuminov",
  "patronymic": "anvarovich",
  "birthDate": "2003-11-14",
  "password": "12345",
  "gender": "MALE",
  "pinfl": "12345678",
  "passportSeries": "AB",
  "passportNumber": "1234",
  "roles": ["ROLE_TEACHER"],
  "schoolId": "7cf08c00-d823-433d-adc6-c05ac07cd21b"
}

### GET BY ID (MODERATOR)
GET localhost:8080/v1/auth/get/moderator/a808584d-6a6b-4c34-9c43-7f97eff0979c
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY5MjA1ODMsImV4cCI6MTc2NzAwNjk4M30.PC_X-3PUULTzc2J3RQec2HSNCO-aPlnx_HoUR0ucunfVGg66YWRKN5ZtDpE8PBlcD-CZFHEGQvQXE1d9zbDyTQ

### GET BY ID (ADMIN)
GET localhost:8080/v1/auth/get/admin/50c20719-05a9-437e-98a0-7a0d91d7bb1d
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NSIsInN1YiI6IjEyMzQ1IiwiaWF0IjoxNzY2OTIyMjAxLCJleHAiOjE3NjcwMDg2MDF9.1JfnouuIBcqsMYliuNN9A9d0zSkuzXLmZZU4u9TD6qhJTpfMN7BsU3ZJZkyZQhqCaTNGpiR2E024BG2710Jskw

### UPDATE (MODERATOR)
PUT localhost:8080/v1/auth/update/moderator/178cf42c-7adc-46cb-ae3a-7462dc586aea
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY5MjA1ODMsImV4cCI6MTc2NzAwNjk4M30.PC_X-3PUULTzc2J3RQec2HSNCO-aPlnx_HoUR0ucunfVGg66YWRKN5ZtDpE8PBlcD-CZFHEGQvQXE1d9zbDyTQ
Content-Type: application/json

{
  "name": "tinchku",
  "roleList": ["ROLE_TEACHER"]
}

### UPDATE (ADMIN)
PUT localhost:8080/v1/auth/update/admin/a3435343-a864-4209-84f9-690bf0f70976
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NSIsInN1YiI6IjEyMzQ1IiwiaWF0IjoxNzY2OTIyMjAxLCJleHAiOjE3NjcwMDg2MDF9.1JfnouuIBcqsMYliuNN9A9d0zSkuzXLmZZU4u9TD6qhJTpfMN7BsU3ZJZkyZQhqCaTNGpiR2E024BG2710Jskw
Content-Type: application/json

{
  "name": "tinchku"
}

### LIST
GET localhost:8080/v1/auth/list?page=0&size=10&school_id=7cf08c00-d823-433d-adc6-c05ac07cd21b&role=ROLE_TEACHER
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY5MjA1ODMsImV4cCI6MTc2NzAwNjk4M30.PC_X-3PUULTzc2J3RQec2HSNCO-aPlnx_HoUR0ucunfVGg66YWRKN5ZtDpE8PBlcD-CZFHEGQvQXE1d9zbDyTQ

### DELETE (MODERATOR)
DELETE localhost:8080/v1/auth/moderator/delete/178cf42c-7adc-46cb-ae3a-7462dc586aea
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY5MjA1ODMsImV4cCI6MTc2NzAwNjk4M30.PC_X-3PUULTzc2J3RQec2HSNCO-aPlnx_HoUR0ucunfVGg66YWRKN5ZtDpE8PBlcD-CZFHEGQvQXE1d9zbDyTQ

### DELETE (ADMIN)
DELETE localhost:8080/v1/auth/admin/delete/a3435343-a864-4209-84f9-690bf0f70976
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY2OTMwMDAwLCJleHAiOjE3NjcwMTY0MDB9.vltcgQrOQQoHY1RVaxyW5My-r_EL_ejcul17nYj5f87lZbhHy21Efeop8-nQM8yrbeISy9GZEppvJAvsEdMNoA

### UPDATE PASSWORD
PUT localhost:8080/v1/auth/update/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY2OTMwMDAwLCJleHAiOjE3NjcwMTY0MDB9.vltcgQrOQQoHY1RVaxyW5My-r_EL_ejcul17nYj5f87lZbhHy21Efeop8-nQM8yrbeISy9GZEppvJAvsEdMNoA

{
  "oldPassword": "12345678",
  "newPassword": "123456789"
}



> {% client.global.set("jwt", response.body.jwt); %}