@moderatorToken = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3Njc1MTgzNTIsImV4cCI6MTc2NzYwNDc1Mn0.klVdSZzjvmnEwjd1kiZGwn2N_tNiY-Ci2iemj0Sjfz_SHTdT6NNetgg7p4CD6DNgZIIXXEeSiyJla8Km__9cvw
@studentToken = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfU1RVREVOVCJdLCJ1c2VybmFtZSI6IjYyMyIsInN1YiI6IjYyMyIsImlhdCI6MTc2NzUxOTEwMCwiZXhwIjoxNzY3NjA1NTAwfQ.r9m2WPTcTSoxbZO7-9LG0B3l1rwihaaKQY7Uwy3-JRErRDiaJpvO549wI1MPlbcsDMEK2GVSqHM5MMVyzFhDVQ
@teacherToken = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVEVBQ0hFUiJdLCJ1c2VybmFtZSI6IjYyIiwic3ViIjoiNjIiLCJpYXQiOjE3Njc1MTkwNzQsImV4cCI6MTc2NzYwNTQ3NH0.tqtE_YC9UcOFWFvCLGgL1VBrH6v_3a8rFqareONPlcIJqOQGTkLHhkp5U66_wbWnX8Trzm4WcDn_b2bR7RdGWQ
@adminToken = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3Njc2MDY0MzcsImV4cCI6MTc2NzY5MjgzN30.qAIpPkbqsca5ZnOrS12ngUYbsDFJiJhuAhRmQ-cpbKzErnMOgb4G2ZBVhDPosUbaS7aurD_Z9AI5yOPTl2miMA


### CREATE GROUP
POST localhost:8080/v1/group/create/admin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3Njc1MTg1NDYsImV4cCI6MTc2NzYwNDk0Nn0.gNp4cWxlbIi4wA56aet4TeRT41D9nu8REuVFKinQk3QqmVrEyp8_pcGY4fTy4hyK-5hzuAWjl6RdkmsTmp1G_w
Content-Type: application/json

{
  "name": "group 101",
  "level": "FIRST",
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e",
  "facultyId": "46709427-28d4-41e9-aa08-d845795172f4",
  "mentorId": "f58eb132-788f-4a84-b9b6-35640fb79bf8"
}

### 6.6 Bitta o'quvchini guruhga biriktirish
PUT http://localhost:8080/v1/group/assign-student?studentId=087bfba3-92a6-4995-a43f-9cab0d74e8e6&groupId=70cba3d8-6802-417f-8335-9e16a658e76e
Authorization: Bearer {{adminToken}}

### 6.7 O'quvchilarni guruhga ommaviy biriktirish (Bulk)
POST http://localhost:8080/v1/group/bulk-assign-students
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "studentIds": [
    "student-uuid-1",
    "student-uuid-2",
    "student-uuid-3"
  ],
  "groupId": "group-uuid-here"
}
### UPDATE
PUT localhost:8080/v1/group/update/admin/7081c246-d3a2-45e7-96dc-95e2ebf961a7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY3MDE3NDc1LCJleHAiOjE3NjcxMDM4NzV9.P5zi3RdhpzxEVWN0JNC3_2_ATx8TUYBs7oO95VOmhURJ6I36A1rzFohdQ5rlFqfqoUdBMJJUQQlFna_jcpugIA
Content-Type: application/json

{
  "name": "group 101"
}

### GET BY ID
GET localhost:8080/v1/group/get-by-id/admin/7081c246-d3a2-45e7-96dc-95e2ebf961a7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY3MDE3NDc1LCJleHAiOjE3NjcxMDM4NzV9.P5zi3RdhpzxEVWN0JNC3_2_ATx8TUYBs7oO95VOmhURJ6I36A1rzFohdQ5rlFqfqoUdBMJJUQQlFna_jcpugIA

### GET ALL
GET localhost:8080/v1/group/get-list/admin/6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e
Authorization: Bearer {{adminToken}}

### GET STUDENT BY GROUP
GET localhost:8080/v1/group/students/7081c246-d3a2-45e7-96dc-95e2ebf961a7
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3OSIsInN1YiI6IjEyMzQ1Njc5IiwiaWF0IjoxNzY3MDE3NDc1LCJleHAiOjE3NjcxMDM4NzV9.P5zi3RdhpzxEVWN0JNC3_2_ATx8TUYBs7oO95VOmhURJ6I36A1rzFohdQ5rlFqfqoUdBMJJUQQlFna_jcpugIA
