### Create region
POST localhost:8080/v1/region/moderator
Content-Type: application/json
Authorization:  Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3Njc3NjU2NDYsImV4cCI6MTc2Nzg1MjA0Nn0.gLfdaAHU_nWd0AhaquFIqPGLrt8BN0THY86iRQw0rKAxVuhzuoy42-V2dk8P8Wv7Uhk9o9fXj2MDorfuzg-LxQ

{
  "orderNumber": 5,
  "nameUz": "Toshkent 5",
  "nameRu": "Ташкент 5",
  "nameEn": "Tashkent 5",
  "regionKey": "tashkent5"
}


### Update region
PUT localhost:8080/v1/region/moderator/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfTU9ERVJBVE9SIl0sInVzZXJuYW1lIjoiMTIzNDU2NyIsInN1YiI6IjEyMzQ1NjciLCJpYXQiOjE3NjY4NDM0NjUsImV4cCI6MTc2NjkyOTg2NX0.p9VdxbWvjcpmA_qqlz0MSKGY63WZSg8VcWXlNFvfVHhZHDlSD1ox17gAz1GNXWctZTi6UeaScpwZMNPm1FaiCw

{
  "orderNumber": 1,
  "nameUz": "Iqtisodiyot11",
  "nameRu": "Экономика11",
  "nameEn": "Economics11",
  "categoryKey": "iqtisodiyot11"
}


### Delete category
DELETE localhost:8080/v1/region/moderator/2
Authorization: Bearer {{jwt}}

### Get region list
GET localhost:8080/v1/region/moderator
Authorization: Bearer {{jwt}}

### Get region by lang
GET localhost:8080/v1/region/lang
Accept-Language: EN
