@admin_token = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3Njc3NjU3MzcsImV4cCI6MTc2Nzg1MjEzN30.PwPestwr0-qDvD7uM6nPnZSjEQFzvTN279oQiVlK6dhiBu_4LkezxGxj5B27EoR7-1wJmQIiavwyKd36WwMHrg

### 2. Dars jadvalini yaratish (Create Schedule)
POST http://localhost:8080/v1/schedule/create/admin
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "schoolId": "a84a424f-7823-4fc6-b9d0-9dde6f00eeb2",
  "groupId": "d2d5a47a-5d76-4d6f-b843-d22afa95d2fc",
  "teacherId": "d1fa6106-1b7a-4f35-b986-4db68fd80446",
  "subjectId": 1,
  "pairNumber": 1,
  "roomId": "104",
  "startTime": "08:30",
  "endTime": "09:50",
  "weekDay": "MONDAY"
}

### 3. Dars jadvalini tahrirlash (Update Schedule)
PUT http://localhost:8080/v1/schedule/update/admin/jadval-uuid-bu-yerga
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "startTime": "09:30",
  "endTime": "10:15",
  "dayOfWeek": "TUESDAY"
}

### 4. Guruh bo'yicha jadvalni olish (Get by Group ID)
GET http://localhost:8080/v1/schedule/get-by-group-id/admin/guruh-uuid-bu-yerga
Authorization: Bearer {{admin_token}}

### 5. O'qituvchi bo'yicha jadvalni olish (Get by Teacher ID)
GET http://localhost:8080/v1/schedule/get-by-teacher-id/admin/f58eb132-788f-4a84-b9b6-35640fb79bf8
Authorization: Bearer {{admin_token}}

### 6. Dars jadvalini o'chirish (Delete Schedule)
DELETE http://localhost:8080/v1/schedule/delete/admin/jadval-uuid-bu-yerga
Authorization: Bearer {{admin_token}}

### GET BY STUDENT ID
GET localhost:8080/v1/schedule/get-student
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfU1RVREVOVCJdLCJ1c2VybmFtZSI6IjYyMyIsInN1YiI6IjYyMyIsImlhdCI6MTc2NzcwNTE2NCwiZXhwIjoxNzY3NzkxNTY0fQ.V_cykp5-YlXxDuogFKchWvcVSyG5RElEXJ9TDAboqoEXT_gp2StCXT2QpBCldju-1yewFDFIqqI42Wqirhsuig

### GET BY TEACHER
GET localhost:8080/v1/schedule/get-teacher