@admin_token = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfQURNSU4iXSwidXNlcm5hbWUiOiIxMjM0NTY3MDEiLCJzdWIiOiIxMjM0NTY3MDEiLCJpYXQiOjE3Njc3MDQ0NDEsImV4cCI6MTc2Nzc5MDg0MX0.jk6SP-XMrRPfW2sSh2hOT2Lcx2FnD5733SEfxq3xZaUKGjJLrk4mSCa52aoHTxqp4_rNB9O8bbtNuDpnigrZUQ

### 2. Dars jadvalini yaratish (Create Schedule)
POST http://localhost:8080/v1/schedule/create/admin
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e",
  "groupId": "70cba3d8-6802-417f-8335-9e16a658e76e",
  "teacherId": "f58eb132-788f-4a84-b9b6-35640fb79bf8",
  "subjectId": 1,
  "roomId": "104",
  "startTime": "08:30",
  "endTime": "09:50",
  "dayOfWeek": "MONDAY"
}

### 3. Dars jadvalini tahrirlash (Update Schedule)
PUT http://localhost:8080/v1/schedule/update/admin/jadval-uuid-bu-yerga
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "startTime": "09:30",
  "endTime": "10:15",
  "dayOfWeek": "TUESDAY"
}

### 4. Guruh bo'yicha jadvalni olish (Get by Group ID)
GET http://localhost:8080/v1/schedule/get-by-group-id/admin/guruh-uuid-bu-yerga
Authorization: Bearer {{admin_token}}

### 5. O'qituvchi bo'yicha jadvalni olish (Get by Teacher ID)
GET http://localhost:8080/v1/schedule/get-by-teacher-id/admin/f58eb132-788f-4a84-b9b6-35640fb79bf8
Authorization: Bearer {{admin_token}}

### 6. Dars jadvalini o'chirish (Delete Schedule)
DELETE http://localhost:8080/v1/schedule/delete/admin/jadval-uuid-bu-yerga
Authorization: Bearer {{admin_token}}

### GET BY STUDENT ID
GET localhost:8080/v1/schedule/get-student
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfU1RVREVOVCJdLCJ1c2VybmFtZSI6IjYyMyIsInN1YiI6IjYyMyIsImlhdCI6MTc2NzcwNTE2NCwiZXhwIjoxNzY3NzkxNTY0fQ.V_cykp5-YlXxDuogFKchWvcVSyG5RElEXJ9TDAboqoEXT_gp2StCXT2QpBCldju-1yewFDFIqqI42Wqirhsuig

### GET BY TEACHER
GET localhost:8080/v1/schedule/get-teacher