@teacher_token = eyJhbGciOiJIUzUxMiJ9.eyJyb2xlIjpbIlJPTEVfVEVBQ0hFUiJdLCJ1c2VybmFtZSI6IjYyIiwic3ViIjoiNjIiLCJpYXQiOjE3Njc2MDY4NjMsImV4cCI6MTc2NzY5MzI2M30.npiwpUH3Ic0ELNtw_Xh2xChwEkipmbYhLFG7y_EjkRY-K_r7Up_egggE9ZtCxE0u6bb5nT3g5LzQnVlI3HCu7w


### 2. Yangi mavzu qo'shish (1-mavzu)
POST http://localhost:8080/v1/work-plan/create
Authorization: Bearer {{teacher_token}}
Content-Type: application/json

{
  "subjectId": 1,
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e",
  "title": "Kirish. Algoritm tushunchasi va uning xossalari",
  "orderNumber": 1
}

### 3. Keyingi mavzuni qo'shish (2-mavzu)
POST http://localhost:8080/v1/work-plan/create
Authorization: Bearer {{teacher_token}}
Content-Type: application/json

{
  "subjectId": 1,
  "schoolId": "6fadf266-484f-4e0f-b77b-7a6e2c7e7f6e",
  "title": "Chiziqli va tarmoqlanuvchi algoritmlar",
  "orderNumber": 2
}

### 4. O'qituvchining o'z fan rejalarini ko'rishi
# Ma'lumotlar orderNumber bo'yicha tartiblangan holda keladi
GET http://localhost:8080/v1/work-plan/my-plan/1
Authorization: Bearer {{teacher_token}}

### 5. Mavzuni o'chirish (Soft Delete)
DELETE http://localhost:8080/v1/work-plan/delete/ish-reja-uuid-bu-yerga
Authorization: Bearer {{teacher_token}}